### ISSUE TITLE
Add support for macOS?

### ISSUE THREAD

**Issue by ghost** [brunomacabeusbr/GridView#1]
Is it possible to add support for macOS.

**Comment by macabeus** [comment]
@beheer7 This pod uses UIKit, and macOS has a complete different UI company library, then is hard to add support for macOS. Maybe is possible to reuse the interface and the algorithm to draw the grid...

**Comment by beheer7** [comment]
@macabeus Yes, for macOS it's AppKit. The only very differents between UIKit and AppKit for this project is UICollectionView and NSCollectionView. 

`Slot` and `GridConfiguration` does not need any change. [GridLayout](https://gist.github.com/beheer7/590a17aa3fd0e02dae15eb60dd8dba35) a few. A lot of changes in [GridViewController](https://gist.github.com/beheer7/209fa84ecd1f1495a8f190aa36225480). Especially the class `GridViewController` is a big one.

Still need to fix registering the cells. If I run it, it crashes because the delegate is null.

I think it is possible to add support for macOS.. it still needs a bit of work..

Checking which OS it is helps a lot with adding Mac support for this project.
```
#if os(iOS) || os(tvOS)
    import UIKit
#elseif os(OSX)
    import AppKit
#endif
```

**Comment by beheer7** [comment]
I'm building macOS support in this [fork](https://github.com/beheer7/GridView). I will push it back to you when it's ready. Only need to make te Example-Mac project part.
