### ISSUE TITLE
mal-aligned grid?

### ISSUE THREAD

**Issue by lingolab2** [brunomacabeusbr/GridView#2]
Thanks for the nice library. One small issue where the grid seems  mal-aligned. 
See https://d.pr/i/u0iXIL for image.

With the foll. gridConfiguration:
```
[Slot(cell: CellMap.self, params: [:]),
            
              Slot(cell: CellChart.self, params: [:]),
              Slot(cell: CellChart.self, params: [:]),
              Slot(cell: CellLogs.self, params: [:])],
            
            [Slot(cell: CellCharacter.self, params: ["race": "troll"]),
             Slot(cell: CellCharacter.self, params: ["race": "elves"]),
             Slot(cell: CellCharacter.self, params: ["race": "undead"]),
             Slot(cell: CellCharacter.self, params: ["race": "merfolk"])]
```
I get a mal-aligned grid.

Am I missing something?

**Comment by macabeus** [comment]
Hello,

This is the expected behaviour. Let's see why...

```swift
[
  [ // first row
    Slot(cell: CellMap.self, params: [:]), // cell Map
    Slot(cell: CellChart.self, params: [:]), // cell Chart 1
    Slot(cell: CellChart.self, params: [:]), // cell Chart 2
    Slot(cell: CellLogs.self, params: [:]) // cell Logs 1
  ],
  [ // second row
    Slot(cell: CellCharacter.self, params: ["race": "troll"]), // cell Char 1
    Slot(cell: CellCharacter.self, params: ["race": "elves"]), // cell Char 2
    Slot(cell: CellCharacter.self, params: ["race": "undead"]), // cell Char 3
    Slot(cell: CellCharacter.self, params: ["race": "merfolk"]) // cell Char 4
  ]
]
```

This grid will have two rows, because the main array have two elements.

```
| |
| |
```

Nice. Then, using "a something like stack" we will put each cell on the grid. Since the first cell, `Map`, [has size 2x2](https://github.com/macabeus/GridView/blob/3b04d750775602312db5c26762a53168211ff359/Example-tvOS/Example-tvOS/CellMap.swift#L17-L18), we will have:

```
| M1 | M1 |
| M1 | M1 |
```

Okay. Let's put the cell `Chat 1`. This cell [has size 2x1](https://github.com/macabeus/GridView/blob/3b04d750775602312db5c26762a53168211ff359/Example-tvOS/Example-tvOS/CellChart.swift#L15-L16), then:

```
| M1 | M1 | C1 | C1 |
| M1 | M1 |
```

Let's put the `Chart 2`...

```
| M1 | M1 | C1 | C1 | C2 | C2 |
| M1 | M1 |
```

Let's put the last cell on the first row, `Logs 1`. This cell [has size 2x1](https://github.com/macabeus/GridView/blob/3b04d750775602312db5c26762a53168211ff359/Example-tvOS/Example-tvOS/CellLogs.swift#L14-L15).

```
| M1 | M1 | C1 | C1 | C2 | C2 | L1 | L1 |
| M1 | M1 |
```

Okay. We finished the first row. Now, let's start the second row putting the cell `Char 1`. This cell [has as size 1x1](https://github.com/macabeus/GridView/blob/3b04d750775602312db5c26762a53168211ff359/Example-tvOS/Example-tvOS/CellCharacter.swift#L15-L16).

```
| M1 | M1 | C1 | C1 | C2 | C2 | L1 | L1 |
| M1 | M1 | X1 |
```

Let's put the `Char 2`...

```
| M1 | M1 | C1 | C1 | C2 | C2 | L1 | L1 |
| M1 | M1 | X1 | X2 |
```

Let's put the `Char 3`...

```
| M1 | M1 | C1 | C1 | C2 | C2 | L1 | L1 |
| M1 | M1 | X1 | X2 | X3 |
```

And finally, the `Char 4`:

```
| M1 | M1 | C1 | C1 | C2 | C2 | L1 | L1 |
| M1 | M1 | X1 | X2 | X3 | X4 |
```

Finish!

You can see that we have a hole on bellow the L1. But it is expected by the algorithm.
This could be a little confused on the begin, but it is **very** flexible and very easy to write.
